compilers:
  - name: clang
    cmake_extra_flags: -DBUILD_TESTING:BOOL=ON -DBUILD_PACKAGE:BOOL=ON
  - name: clang
    build_type: Debug
    cmake_extra_flags: -DBUILD_TESTING:BOOL=ON -DBUILD_PACKAGE:BOOL=ON

